### PR TITLE
Compatible with ue5

### PR DESCRIPTION
**Pull request by AiMiDi**

### CODE REVIEW

**Review by MalikHaroonKhokhar — COMMENTED** [review]
I have used the code with the changes its not compatible with unreal engine 5.3

**Comment by Fransferdy** [comment]
It is compatible with UE 5.1.

**Comment by libreliu** [comment]
Parts of the incompatibiliy owes to the introduction of 16-bit skin weights in UE5.3.
Details could be found at [UnrealEngine @ e2210cb](https://github.com/EpicGames/UnrealEngine/commit/e2210cb0242a691c87023b046d430b651dd2988d). This afftects the import behavior from `FSkinWeightInfo` to `FSkinWeightVertexBuffer`, and the latter now requires a uint16 encoded weight, with the range 0 - 65535 instead of 0 - 255. The import code would throw away the lower 8 bits of the uint16 encoded weight if the actual storage type is 8 bit, which is exactly the case when running the plugin unmodified for UE5.3.

**Comment by AndreaCatania** [comment]
@libreliu thanks for these info. Feel free to open a PR if you have this working already.

**Comment by AiMiDi** [comment]
> Parts of the incompatibiliy owes to the introduction of 16-bit skin weights in UE5.3. Details could be found at [UnrealEngine @ e2210cb](https://github.com/EpicGames/UnrealEngine/commit/e2210cb0242a691c87023b046d430b651dd2988d). This afftects the import behavior from `FSkinWeightInfo` to `FSkinWeightVertexBuffer`, and the latter now requires a uint16 encoded weight, with the range 0 - 65535 instead of 0 - 255. The import code would throw away the lower 8 bits of the uint16 encoded weight if the actual storage type is 8 bit, which is exactly the case when running the plugin unmodified for UE5.3.

Thanks for the suggestion, changes have been [submitted](https://github.com/AndreaCatania/RuntimeSkeletalMeshGenerator/pull/24/commits/107a2749e4aca72b8671b162cb50cfea2efd192f).

**Comment by AndreaCatania** [comment]
Thanks!

**Comment by AiMiDi** [comment]
Thanks for the merger, but I haven't tested it in detail yet, I hope someone can help test it, and I will fix it.

**Comment by libreliu** [comment]
> Thanks for the merger, but I haven't tested it in detail yet, I hope someone can help test it, and I will fix it.

I tested `DecomposeSkeletalMesh(...) -> GenerateSkeletalMeshComponent(..)` and it works with a hand-crafted tiny model under UE5.3. Didn't tested `FRuntimeAnimationGenerator` though.

**Comment by libreliu** [comment]
Another 2 bugs that I discovered: 
1. Should add `Surface.MaterialIndex = RenderSection.MaterialIndex;` in `DecomposeSkeletalMesh` to initialize the MaterialIndex, otherwise this may init to some garbage value and hence break the FMeshSurface data.
2. Should use Mesh RefSkeleton in some of the cases (e.g. `SkeletalMesh->SetRefSkeleton(ParentComponent->GetSkeletalMeshAsset()->GetRefSkeleton());`), otherwise the bone indices will be wrong, leading to incorrect rendering on UE5 Quinn with UE5_Mannequinn Skeleton.

(Will file a PR if I have time..!)

**Pull request merged**
